apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwoot
  labels:
    app: chatwoot

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatwoot
  template:
    metadata:
      labels:
        app: chatwoot
    spec:
      containers:
        - name: rails
          image: alnafi_chatwoot:latest
          envFrom:
            - configMapRef:
                name: chatwoot-config
            - secretRef:
                name: chatwoot-secrets
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
        - name: sidekiq
          image: alnafi/chatwoot:latest
          envFrom:
            - configMapRef:
                name: chatwoot-config
            - secretRef:
                name: chatwoot-secrets
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "sidekiq"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "sidekiq"]
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chatwoot
spec:
  selector:
    app: chatwoot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

