apiVersion: apps/v1


kind: Deployment

metadata:
  name: chatwoot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: chatwoot

  template:
    metadata:
      labels:
        app: chatwoot

    spec:
      containers:

      - name: rails
        image: alnafi_chatwoot
        env:
        - name: NODE_ENV
          value: "production"
        - name: RAILS_ENV
          value: "production"
        - name: INSTALLATION_ENV
          value: "docker"
        volumeMounts:
        - name: storage
          mountPath: /app/storage
        ports:
        - containerPort: 3000
        command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi


      - name: sidekiq
        image: alnafi_chatwoot

        env:
        - name: NODE_ENV
          value: "production"
        - name: RAILS_ENV
          value: "production"
        - name: INSTALLATION_ENV
          value: "docker"

        command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi


      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: chatwoot-pvc




---



apiVersion: v1
kind: Service
metadata:
  name: chatwoot
spec:
  selector:
    app: chatwoot
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP



---



# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: chatwoot-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: chatwoot
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 75
  
#       target:
#         type: Utilization
#         averageUtilization: 75

