apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      imagePullSecrets:
        - name: ecr-key
      containers:
        - name: rails
          image: 454848198532.dkr.ecr.us-east-1.amazonaws.com/alnafi_chatwoot:latest
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: RAILS_ENV
              value: "production"
            - name: INSTALLATION_ENV
              value: "docker"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: storage
              mountPath: /app/storage
        - name: sidekiq
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          image: 454848198532.dkr.ecr.us-east-1.amazonaws.com/alnafi_chatwoot:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: RAILS_ENV
              value: "production"
            - name: INSTALLATION_ENV
              value: "docker"
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          volumeMounts:
            - name: storage
              mountPath: /app/storage
      volumes:
        - name: storage
          hostPath:
            path: /data/storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379

          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"

          volumeMounts:
            - name: redis
              mountPath: /data/redis
      volumes:
        - name: redis
          hostPath:
            path: /data/redis

---

apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

